version: '3'

services:

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=camunda
      - POSTGRES_PASSWORD=camunda
    ports:
      - '5432:5432'
    volumes:
      - psql:/var/lib/postgresql/data

  camunda:
    image: camunda/camunda-bpm-platform
    environment:
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://postgres:5432/camunda
      - DB_USERNAME=camunda
      - DB_PASSWORD=camunda
      - WAIT_FOR=postgres:5432        # waiting for psql instance to be ready
    links:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 5

  spring-app:
    image: alandademo:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    restart: on-failure
    depends_on:
      - camunda
    links:
      - camunda

volumes:
  psql:
    driver: local
